name: affection_alerts
description: "Daily affection alerts"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_openai: ^5.0.0
  envied: ^0.5.3
  build_runner: ^2.4.8
  intl: ^0.19.0
  flutter_local_notifications: ^16.3.2
  workmanager: ^0.5.2
  timezone: ^0.9.2
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/whatsapp_chat.txt

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
